# puerto 3306 al host
spring.datasource.url=jdbc:mysql://localhost:3306/panaderia_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#credenciales de usuario personalizado
spring.datasource.username=user_panaderia
spring.datasource.password=password123

#uso del driver de MySQL 8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate - actualizamos el dialecto a MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false